name: Deploy to Vercel

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy
        run: npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --yes
        env:
          VERCEL_ORG_ID: team_oVMnoQQc9RvcYcuTRuBFiP0S
          VERCEL_PROJECT_ID: prj_KJOcPx7atrVXMquujv15ItjmV5U0
